language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm run pretest

script:
    - npm run test
